<?php require_once '../../components/header/header.php'; ?>
<?php require_once '../../components/navigation/navigation.php'; ?>
<?php require_once '../../components/hero/hero.php'; ?>
<?php require_once '../../components/chef/chef.php'; ?>
<?php require_once '../../components/ouverture/ouverture.php'; ?>
<?php require_once '../../components/philosophie/philosophie.php'; ?>
<?php require_once '../../components/histoire/histoire.php'; ?>
<?php require_once '../../components/reseaux/reseaux.php'; ?>
<?php require_once '../../components/contact/contact.php'; ?>
<?php require_once '../../components/footer/footer.php'; ?>
